# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=80)),
                ('secondName', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('isPhysical', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nType', models.CharField(max_length=50)),
                ('benefit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('cost', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotebookOrder',
            fields=[
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.Order')),
                ('quantity', models.PositiveIntegerField()),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Notebook')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Page')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Client'),
        ),
    ]
